/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as scwSol from "./SCW.sol";
export type { scwSol };
import type * as algorithms from "./algorithms";
export type { algorithms };
export type { DkimChecker } from "./DkimChecker";
export type { Migrations } from "./Migrations";
