/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  DkimCheckerInterface,
  DkimCheckerInterfaceInterface,
} from "../../../contracts/SCW.sol/DkimCheckerInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_selector",
        type: "string",
      },
      {
        internalType: "string",
        name: "_domain",
        type: "string",
      },
      {
        internalType: "bytes",
        name: "_sig",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "_canonicalizedHeader",
        type: "bytes",
      },
    ],
    name: "verifyRSASHA256",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class DkimCheckerInterface__factory {
  static readonly abi = _abi;
  static createInterface(): DkimCheckerInterfaceInterface {
    return new utils.Interface(_abi) as DkimCheckerInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DkimCheckerInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as DkimCheckerInterface;
  }
}
