/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ED25519Interface extends utils.Interface {
  functions: {
    "ecAddVec(uint256[2],uint256[2])": FunctionFragment;
    "scalarMult(uint256[2],uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "ecAddVec" | "scalarMult"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ecAddVec",
    values: [
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "scalarMult",
    values: [
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "ecAddVec", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "scalarMult", data: BytesLike): Result;

  events: {};
}

export interface ED25519 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ED25519Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ecAddVec(
      _a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _b: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      overrides?: CallOverrides
    ): Promise<[[BigNumber, BigNumber]]>;

    scalarMult(
      point: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      s: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;
  };

  ecAddVec(
    _a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    _b: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  scalarMult(
    point: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    s: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  callStatic: {
    ecAddVec(
      _a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _b: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    scalarMult(
      point: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      s: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;
  };

  filters: {};

  estimateGas: {
    ecAddVec(
      _a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _b: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    scalarMult(
      point: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      s: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ecAddVec(
      _a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _b: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    scalarMult(
      point: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      s: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
