/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface DkimCheckerInterfaceInterface extends utils.Interface {
  functions: {
    "verifyRSASHA256(string,string,bytes,bytes)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "verifyRSASHA256"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "verifyRSASHA256",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "verifyRSASHA256",
    data: BytesLike
  ): Result;

  events: {};
}

export interface DkimCheckerInterface extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DkimCheckerInterfaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    verifyRSASHA256(
      _selector: PromiseOrValue<string>,
      _domain: PromiseOrValue<string>,
      _sig: PromiseOrValue<BytesLike>,
      _canonicalizedHeader: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  verifyRSASHA256(
    _selector: PromiseOrValue<string>,
    _domain: PromiseOrValue<string>,
    _sig: PromiseOrValue<BytesLike>,
    _canonicalizedHeader: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    verifyRSASHA256(
      _selector: PromiseOrValue<string>,
      _domain: PromiseOrValue<string>,
      _sig: PromiseOrValue<BytesLike>,
      _canonicalizedHeader: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    verifyRSASHA256(
      _selector: PromiseOrValue<string>,
      _domain: PromiseOrValue<string>,
      _sig: PromiseOrValue<BytesLike>,
      _canonicalizedHeader: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    verifyRSASHA256(
      _selector: PromiseOrValue<string>,
      _domain: PromiseOrValue<string>,
      _sig: PromiseOrValue<BytesLike>,
      _canonicalizedHeader: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
