/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DkimCheckerInterface } from "./DkimCheckerInterface";
export type { SCW } from "./SCW";
export type { SCWDeployer } from "./SCWDeployer";
